### ISSUE TITLE
Error: Cannot create a string longer than 0x3fffffe7 characters

### ISSUE THREAD

**Issue by Reedyuk** [i3h/download-release-asset#3]
When running this action, im getting this error, i know the zip file is large, but should be able to handle this.

```
Run i3h/download-release-asset@v1.1.0
  with:
    owner: firebase
    repo: firebase-ios-sdk
    tag: 6.17.0
    file: Firebase-6.17.0.zip
    token: ***
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/jdk/8.0.252/x64
    JAVA_HOME_8.0.252_x64: /Users/runner/hostedtoolcache/jdk/8.0.252/x64
buffer.js:776
    return this.utf8Slice(start, end);
                ^

Error: Cannot create a string longer than 0x3fffffe7 characters
    at Buffer.toString (buffer.js:776:17)
    at Request.<anonymous> (/Users/runner/runners/2.263.0/work/_actions/i3h/download-release-asset/v1.1.0/dist/index.js:58713:39)
    at Request.emit (events.js:215:7)
    at IncomingMessage.<anonymous> (/Users/runner/runners/2.263.0/work/_actions/i3h/download-release-asset/v1.1.0/dist/index.js:58661:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_STRING_TOO_LONG'
}
```

**Comment by i3h** [comment]
I have fixed this problem. Please update actions release version and it should work now.

```
Run i3h/download-release-asset@v1
  with:
    owner: firebase
    repo: firebase-ios-sdk
    tag: 6.17.0
    file: Firebase-6.17.0.zip

Run ls -lha
total 1.1G
drwxr-xr-x 2 runner docker 4.0K Jul  2 08:52 .
drwxr-xr-x 3 runner docker 4.0K Jul  2 08:52 ..
-rw-r--r-- 1 runner docker 1.1G Jul  2 08:53 Firebase-6.17.0.zip
```
